Repository adopted-ember-addons/ember-light-table, pull requests merged in 2022-07, with the labels that each got.

#779 Remove Bower configuration
  .bowerrc
  .npmignore
Labels: internal

#780 Drop node 10
  .github/workflows/ci.yml
  .travis.yml
  README.md
  package.json
Labels: breaking

#781 Update Fakerjs and fix dummy app user data
  package.json
  tests/dummy/mirage/factories/user.js
  yarn.lock
Labels: demo

#784 Remove fix-proto - Drop support for IE < 10
  addon/classes/Column.js
  addon/classes/Row.js
  addon/classes/Table.js
  addon/utils/fix-proto.js
  tests/unit/utils/fix-proto-test.js
Labels: breaking

#785 Update repo URLs in documentation and code
  CONTRIBUTING.md
  README.md
  addon/index.js
  addon/mixins/table-header.js
  package.json
  tests/dummy/app/templates/application.hbs
  yuidoc.json
Labels: documenation

#786 Convert yuidoc code snippets to angle brackets
  addon/components/light-table.js
  addon/components/lt-body.js
  addon/components/lt-foot.js
  addon/components/lt-head.js
Labels: documenation

#790 Import computed macros directly
  .github/workflows/ci.yml
  addon/classes/Column.js
  addon/classes/Table.js
  addon/components/cells/base.js
  addon/components/columns/base.js
  addon/components/light-table.js
  addon/components/lt-body.js
  addon/components/lt-row.js
  addon/mixins/table-header.js
  package.json
  tests/dummy/app/components/base-table.js
  tests/dummy/app/components/cookbook/client-side-table.js
  tests/dummy/app/components/rows/selectable-table.js
  yarn.lock
Labels: bug

#791 Fix implicit `this`, runloop, and assign issues
  .prettierrc.js
  .template-lintrc.js
  addon/-private/global-options.js
  addon/classes/Table.js
  addon/components/lt-body.js
  addon/mixins/draggable-column.js
  addon/templates/components/cells/base.hbs
  addon/templates/components/columns/base.hbs
  addon/templates/components/light-table.hbs
  addon/templates/components/lt-body.hbs
  addon/templates/components/lt-foot.hbs
  addon/templates/components/lt-head.hbs
  addon/templates/components/lt-row.hbs
  addon/templates/components/lt-scaffolding-row.hbs
  addon/templates/components/lt-scrollable.hbs
  addon/templates/components/lt-spanned-row.hbs
  package.json
  tests/dummy/mirage/config.js
  tests/dummy/mirage/factories/user.js
  tests/dummy/mirage/models/user.js
  tests/dummy/mirage/serializers/application.js
  tests/integration/components/light-table-occlusion-test.js
  tests/integration/components/light-table-test.js
  tests/integration/components/light-table/cells/base-test.js
  tests/integration/components/light-table/columns/base-test.js
  tests/integration/components/lt-body-occlusion-test.js
  tests/integration/components/lt-body-test.js
  tests/integration/components/lt-head-test.js
  tests/integration/components/lt-infinity-test.js
  tests/integration/components/lt-scaffolding-row-test.js
  tests/integration/components/lt-spanned-row-test.js
  yarn.lock
Labels: internal

#792 Update ember-scrollable
  addon/components/lt-body.js
  addon/templates/components/lt-scrollable.hbs
  package.json
  tests/integration/components/light-table-occlusion-test.js
  tests/integration/components/light-table-test.js
  yarn.lock
Labels: internal

#793 Convert dummy app
  package.json
  tests/dummy/app/adapters/application.js
  tests/dummy/app/components/base-table.js
  tests/dummy/app/components/code-panel.js
  tests/dummy/app/components/colored-row.js
  tests/dummy/app/components/columns/draggable-table.js
  tests/dummy/app/components/columns/grouped-table.js
  tests/dummy/app/components/columns/resizable-table.js
  tests/dummy/app/components/cookbook/client-side-table.js
  tests/dummy/app/components/cookbook/custom-row-table.js
  tests/dummy/app/components/cookbook/custom-sort-icon-table.js
  tests/dummy/app/components/cookbook/horizontal-scrolling-table.js
  tests/dummy/app/components/cookbook/occluded-table.js
  tests/dummy/app/components/cookbook/paginated-table.js
  tests/dummy/app/components/cookbook/table-actions-table.js
  tests/dummy/app/components/materialize-icon.js
  tests/dummy/app/components/responsive-table.js
  tests/dummy/app/components/rows/expandable-table.js
  tests/dummy/app/components/rows/selectable-table.js
  tests/dummy/app/components/scrolling-table.js
  tests/dummy/app/components/simple-table.js
  tests/dummy/app/models/user.js
  tests/dummy/app/routes/table-route.js
  tests/dummy/app/templates/components/cookbook/client-side-table.hbs
  tests/dummy/app/templates/components/materialize-icon.hbs
  tests/dummy/app/templates/components/scrolling-table.hbs
Labels: internal

#797 Minor icon fixes
  tests/dummy/app/components/rows/selectable-table.js
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/components/row-toggle.hbs
Labels: internal

#798 Fix onScrolledToBottom / use render modifiers
  addon/components/lt-body.js
  addon/templates/components/lt-body.hbs
  tests/dummy/app/components/code-panel.js
  tests/integration/components/light-table-test.js
Labels: bug

#799 Tweak some icons
  config/icons.js
  package.json
  tests/dummy/app/templates/components/rows/selectable-table.hbs
  tests/dummy/app/templates/components/user-actions.hbs
  yarn.lock
Labels: internal

#800 Fix responsive functionality
  addon/components/light-table.js
  package.json
  tests/helpers/responsive.js
Labels: bug

#801 Make embroider-safe
  addon/classes/Column.js
  addon/classes/Row.js
  addon/classes/Table.js
  addon/components/cells/base.hbs
  addon/components/cells/base.js
  addon/components/columns/base.hbs
  addon/components/columns/base.js
  addon/components/light-table.hbs
  addon/components/light-table.js
  addon/components/lt-body.hbs
  addon/components/lt-body.js
  addon/components/lt-column-resizer.hbs
  addon/components/lt-column-resizer.js
  addon/components/lt-foot.hbs
  addon/components/lt-foot.js
  addon/components/lt-head.hbs
  addon/components/lt-head.js
  addon/components/lt-infinity.hbs
  addon/components/lt-infinity.js
  addon/components/lt-row.hbs
  addon/components/lt-row.js
  addon/components/lt-scaffolding-row.hbs
  addon/components/lt-scaffolding-row.js
  addon/components/lt-scrollable.hbs
  addon/components/lt-scrollable.js
  addon/components/lt-spanned-row.hbs
  addon/components/lt-spanned-row.js
  addon/templates/components/lt-head.hbs
  package.json
  tests/dummy/app/components/code-panel.hbs
  tests/dummy/app/components/code-panel.js
  tests/dummy/app/components/code-snippet.hbs
  tests/dummy/app/components/columns/draggable-table.hbs
  tests/dummy/app/components/columns/grouped-table.hbs
  tests/dummy/app/components/columns/resizable-table.hbs
  tests/dummy/app/components/cookbook/client-side-table.hbs
  tests/dummy/app/components/cookbook/custom-row-table.hbs
  tests/dummy/app/components/cookbook/custom-sort-icon-table.hbs
  tests/dummy/app/components/cookbook/horizontal-scrolling-table.hbs
  tests/dummy/app/components/cookbook/index-list.hbs
  tests/dummy/app/components/cookbook/occluded-table.hbs
  tests/dummy/app/components/cookbook/paginated-table.hbs
  tests/dummy/app/components/cookbook/table-actions-table.hbs
  tests/dummy/app/components/expanded-row.hbs
  tests/dummy/app/components/fa-icon-wrapper.hbs
  tests/dummy/app/components/materialize-icon.hbs
  tests/dummy/app/components/no-data.hbs
  tests/dummy/app/components/responsive-expanded-row.hbs
  tests/dummy/app/components/responsive-table.hbs
  tests/dummy/app/components/row-toggle.hbs
  tests/dummy/app/components/rows/expandable-table.hbs
  tests/dummy/app/components/rows/selectable-table.hbs
  tests/dummy/app/components/scrolling-table.hbs
  tests/dummy/app/components/simple-table.hbs
  tests/dummy/app/components/table-loader.hbs
  tests/dummy/app/components/user-actions.hbs
  tests/dummy/app/components/user-avatar.hbs
  tests/dummy/app/templates/components/user-avatar.hbs
  yarn.lock
Labels: internal

#803 Fix scroll to row
  addon/components/lt-body.hbs
  addon/components/lt-body.js
Labels: bug

#804 Remove enableSync option, require updating table rows manually
  addon/-private/sync-array-proxy.js
  addon/classes/Table.js
  addon/index.js
  tests/dummy/app/components/base-table.js
  tests/dummy/app/components/cookbook/client-side-table.js
  tests/unit/classes/table-test.js
Labels: breaking

#805 Make light-table tagless
  addon/components/light-table.hbs
  addon/components/light-table.js
Labels: breaking

#806 Convert dummy app to glimmer components
  package.json
  tests/dummy/app/adapters/application.js
  tests/dummy/app/components/base-table.js
  tests/dummy/app/components/code-panel.js
  tests/dummy/app/components/columns/draggable-table.js
  tests/dummy/app/components/columns/grouped-table.js
  tests/dummy/app/components/columns/resizable-table.js
  tests/dummy/app/components/cookbook/client-side-table.js
  tests/dummy/app/components/cookbook/custom-row-table.js
  tests/dummy/app/components/cookbook/custom-sort-icon-table.js
  tests/dummy/app/components/cookbook/horizontal-scrolling-table.js
  tests/dummy/app/components/cookbook/occluded-table.js
  tests/dummy/app/components/cookbook/paginated-table.js
  tests/dummy/app/components/cookbook/table-actions-table.js
  tests/dummy/app/components/materialize-icon.js
  tests/dummy/app/components/responsive-table.js
  tests/dummy/app/components/rows/expandable-table.js
  tests/dummy/app/components/rows/selectable-table.js
  tests/dummy/app/components/scrolling-table.js
  tests/dummy/app/components/simple-table.js
  tests/dummy/app/models/user.js
  tests/dummy/app/routes/table-route.js
Labels: internal
